# Generated by Django 2.0.7 on 2018-07-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=''),
        ),
    ]
