# Generated by Django 2.0.7 on 2018-07-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='is_favorite',
        ),
    ]
